import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { alata, josefin_sans } from './fonts';

export const metadata = {
	title: 'Loopstudios',
	description: 'Generated by create next app',
	icons: {
		icon: '/images/favicon.ico',
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			className={`${alata.variable} ${josefin_sans.variable} scroll-smooth`}
		>
			<body className='font-mono'>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
